### ISSUE TITLE
Shallow comparison causing problems with DateParam

### ISSUE THREAD

**Issue by mattsenior** [pbeshai/use-query-params#100]
Hi! I’m having trouble using `DateParam`, e.g.:

```js
const [date, setDate] = useQueryParam('date', DateParam);
```

I’m finding that the `date` value doesn’t update when the URL changes from one date to another.

The `DateParam.decode` function is working correctly and returning a new `Date` matching the date in the URL.

It looks like a shallow comparison is then being used inside `useQueryParam` to detect changes, but unfortunately this doesn’t work with `Date` objects, as they always appear the same. (I’m pretty sure this is correct but please correct me if I’m wrong)

I put a quick example up here https://codesandbox.io/s/priceless-browser-2zkun?file=/src/App.tsx

One idea to fix this could be changing the API for the parameter definition objects from `{ encode, decode }` to `{ encode, decode, equals }`, where the `equals: (a, b) => boolean` comparator function is used for change detection. This could default to `shallowCompare` to keep the current behaviour, but could be optionally specified as appropriate, e.g.:

- `equals: (a, b) => a.getTime() === b.getTime()` for DateParam
- `equals: Object.is` for a custom param type that needs strict comparison

Cheers

PS Thanks for writing these hooks in the first place

**Comment by pbeshai** [comment]
Wow what a wonderful world we all live in. The equals method seems like a reasonable approach, will work for Moment types and other things with their own equals method too. Let me think about it a bit and will hopefully release a fix soon

**Comment by pbeshai** [comment]
Fixed in v1.1.3, thank you! 🙏  DateParam and DateTimeParam should work now (via `equals`)

**Comment by evrimfeyyaz** [comment]
I just realized the bug an hour ago, and came here to check if anyone else had the same issue. Turns out it's already been fixed. Thanks for the quick fix @pbeshai!

**Comment by pbeshai** [comment]
Thank you :) it was a really well written issue though so shoutout to @mattsenior for taking the initiative.

**Comment by mattsenior** [comment]
@pbeshai Thanks for fixing so quickly
