### ISSUE TITLE
UseEffect won't detect change when a default is set

### ISSUE THREAD

**Issue by devinWin** [pbeshai/use-query-params#102]
I'm wanting to set the default array to 'Active' like so:
`const [query, setQuery] = useQueryParams({ myStatus: withDefault(ArrayParam, ['Active']) });`

then when i empty out the array:
`setQuery({ ...query, 'myStatus': [] });`

my useEffect doesn't get triggered:
```
 useEffect(() => {
  debugger
 }, [JSON.stringify(myStatus)])
```

Is there something i'm not doing correctly, or is this a bug?

**Comment by pbeshai** [comment]
Hi, if you put together a codesandbox reproducing this issue I can help figure it out, but there's not enough here to go on.

Also, by the way, by default setQuery uses pushIn so you don't have to do `...query` - the rest of the query will be kept and only the values specified will change.

**Comment by devinWin** [comment]
I've actually worked around the issue, ah good tip on the pushIn.  Thanks!
