### ISSUE TITLE
`useQueryParams` should an error or warning without context provider configured

### ISSUE THREAD

**Issue by ilovett** [pbeshai/use-query-params#103]
I just spent hours debugging an issue because I forgot that my test harness providers were different from my app providers.  I found that `setLocation` was a noop after a while and then it clicked.  Might help users resolve this issue sooner by logging or throwing an error in this case.

**Comment by pbeshai** [comment]
Hmm, are you on the latest version? I thought we added that here:

https://github.com/pbeshai/use-query-params/blob/master/src/LocationProvider.tsx#L26-L32

**Comment by pbeshai** [comment]
AhI think that is a buggy implementation since the default value is not undefined, it is the shell objects set directly above. Thanks for bringing this up

**Comment by ilovett** [comment]
> Hmm, are you on the latest version? I thought we added that here:
> 
> https://github.com/pbeshai/use-query-params/blob/master/src/LocationProvider.tsx#L26-L32

1.1.3

**Comment by ilovett** [comment]
Yea `NODE_ENV` would have been `test`

**Comment by pbeshai** [comment]
Cool thanks, we should switch it to check != production and make it actually do a proper check 😅

**Comment by pbeshai** [comment]
Fixed in v1.1.8
