### ISSUE TITLE
Preserve current query string when linking

### ISSUE THREAD

**Issue by samselikoff** [pbeshai/use-query-params#105]
I was wondering if there was an idiomatic way to construct Links that preserve the current value of the query string.

Here's what I did using React Router:

```js
export default function () {
  let location = useLocation();

  return (
    <Link to={`/${listId}${location.search}`}>
      List {listId}
    </Link>
  )
}
```

But I was wondering if useQueryParams has any API for "the current serialized string" or if this is an OK approach!

If so I'd be happy to add it as a small example to the Readme, I think it could save a future traveler some time.

**Comment by pbeshai** [comment]
I haven't dealt with this enough yet to have a good general solution yet. Your approach seems fine to me. Sometimes I've made links where I only want a subset of the parameters to be included. Typically involves using `useLocation()` (from react-router), `parse` (from query-string) and `omit` or `pick` from lodash.

I think it's fine to just leave this conversation as an issue instead of putting it in the README for now.

**Comment by evrimfeyyaz** [comment]
Here is the function that I use for getting a "canonical URL." It's useful when you want to remove unnecessary query parameters, such as referral parameters, from a URL.

```ts
/**
 * Returns a canonical URL based on a given URL.
 *
 * @example
 * // Returns "https://covid19.evrim.io/test?a=1"
 * getCanonicalUrl("www.example.com/test?a=1&b=2", "https://covid19.evrim.io", ["a"]);
 *
 * @param url The URL to convert to a canonical URL, e.g. "www.example.com/test?a=1&b=2".
 * @param baseUrl The base URL to use. If this is different than the base URL of the `url`
 *   argument, then this replaces it.
 * @param paramsToKeep The query parameters to keep in the canonical URL. For example, you might
 *   want to remove "ref=some_website" from the canonical URL.
 */
export function getCanonicalUrl(url: string, baseUrl: string, paramsToKeep?: string[]): string {
  const parsedUrl = queryString.parseUrl(url);
  let { query } = parsedUrl;
  const urlWithoutQuery = parsedUrl.url;

  const path = (urlWithoutQuery.match(/^(?:\w*):*\/{0,2}(?:.+)\/(\w+)$/) ?? ["", ""])[1];

  if (paramsToKeep != null) {
    query = paramsToKeep.reduce<ParsedQuery>((filteredQuery, param) => {
      if (param in query) {
        filteredQuery[param] = query[param];
      }

      return filteredQuery;
    }, {});
  }

  const urlQueryString = queryString.stringify(query);

  if (urlQueryString === "") {
    return getAbsoluteUrl(baseUrl, path);
  }

  return getAbsoluteUrl(baseUrl, `${path}?${urlQueryString}`);
}
```
