### ISSUE TITLE
Unable to test using window.history.replaceState

### ISSUE THREAD

**Issue by cmdcolin** [pbeshai/use-query-params#106]
Hi there, thanks for the great library
Not sure if this has been addressed already but I previously used window.history.replaceState

In 0.4.6 this worked from something like a plain create-react-app

App.js
```
import React from 'react';
import logo from './logo.svg';
import './App.css';
import {useQueryParam,StringParam} from 'use-query-params'

function App() {
  const [config,setConfig] = useQueryParam('config',StringParam)
  console.log(config)
  return <p>Hello world</p>
}

export default App;
```

App.test.js
```
import React from 'react';
import { render } from '@testing-library/react';
import App from './App';

test('renders learn react link', () => {
  window.history.replaceState({},'','?config=test')
  const { getByText } = render(<App />);
  const linkElement = getByText(/hello/i);
  expect(linkElement).toBeInTheDocument();
});

```

The config is undefined in 1.1.3 but works in 0.4.6

The only workaround I could think of was copying a lot of the code in the helpers inside this repo and using the QueryParamProvider. Is that excessive?

**Comment by cmdcolin** [comment]
Probably similar to #37

**Comment by pbeshai** [comment]
If you're using react-router, you can look at the examples dir to see how you can test it: https://github.com/pbeshai/use-query-params/blob/master/examples/react-router/src/App.test.tsx

There's an example in the reach-router example too.

If you're not using either of those, I'd suggest you wrap your <App> with a QueryParamProvider that has a mocked history passed in as a prop that you can test against.

**Comment by cmdcolin** [comment]
Thanks for this

I don't use react router but I think I got it with QueryParamProvider. Appreciate it!

    <QueryParamProvider location={{search:'?config=test'}}>
        <App />
    </QueryParamProvider>

I had sort of gotten confused because I thought I needed to use the history prop for QueryParamProvider due to naming similarity to window.history.replaceState but this worked fine

**Comment by cmdcolin** [comment]
There could be a thing with typescript interface where it doesn't want me to only specify search like this without other params, I dunno what you think but you could maybe make the params to location optional
