### ISSUE TITLE
Option to change default for UrlUpdateType

### ISSUE THREAD

**Issue by damnitrahul** [pbeshai/use-query-params#109]
Is there any way to change the default for `UrlUpdateType`?

I want to use `replaceIn` all over my project.
How can I make it the default, so I don't have to pass `UrlUpdateType` every time I want to update the URL.

**Comment by pbeshai** [comment]
You can wrap the hook in your own hook I'd imagine. Something like:

```js
const useQueryParamsReplace = (config) => {
  const [query, setQuery] = useQueryParams(config);

  const setQueryReplace = (newQuery, updateType = 'replace') => 
    setQuery(newQuery, updateType);

  return [query, setQueryReplace]
}
```
