### ISSUE TITLE
does not work in IE 11

### ISSUE THREAD

**Issue by Cloudo** [pbeshai/use-query-params#11]
hi. thanks for nice hook!
I wonder why tsconfig target is "es2018"? are there any issues with transpiling to "es5"? 
at the moment we have no IE support =(

**Comment by pbeshai** [comment]
Oh hmm, I didn't realize this. I'll take a look

**Comment by pbeshai** [comment]
Switched to es5 target in v0.3.2. Thanks for bringing this up!
