### ISSUE TITLE
useQueryParam hook broken for DateParam with default value

### ISSUE THREAD

**Issue by LandazuriPaul** [pbeshai/use-query-params#111]
Hi and thank you very much for this library which is really helpful!

I want to report an issue regarding a potential default `DateParam` value when using the `useQueryParam` hook.

When using the hook without any default value, everything works fine. But when a default value is set using the `withDefault` helper for a `DateParam`, it seems like the `useQueryParam` is partly broken.

```ts
const [date, setDate] = useQueryParam(
    "date",
    withDefault(DateParam, new Date())
  );
```
In this case, the setter still updates the URL value but the getter always returns the initial value and doesn't update as expected.

If I misunderstood something about the library's API, I'm sorry to bother. But otherwise, I reckon this isn't intended.

To reproduce the bug, I created [this codesandbox](https://codesandbox.io/s/use-query-params-default-date-bug-f7vzt).

Have a great one!

**Comment by pbeshai** [comment]
Thank you, this is because withDefault forgot to include the `equals` property on the parameter. I'll publish a fix momentarily, but you can also get around it currently (I believe) with:

```
{ ...withDefault(DateParam, new Date()), equals: DateParam.equals } 
```

**Comment by pbeshai** [comment]
Fixed in v1.1.4

**Comment by LandazuriPaul** [comment]
Wow that was incredibly fast to answer back and fix the issue! Thank you very much!

**Comment by hoetmaaiers** [comment]
In my current version `use-query-params@2.2.1` the equals param has to be explicitly set again. Is the previous fix not sufficient or gone?

My example:

```
const [query, setQuery] = useQueryParams({
  timestamp: { ...withDefault(DateTimeParam, new Date()), equals: DateParam.equals },
})
```

Without the equals definition, the timestamp is recalculated in combination with a useQuery request depending on the `timestamp` parameter.
