### ISSUE TITLE
Bug: UseQueryParams crush then add new filters after page mount

### ISSUE THREAD

**Issue by sanchezweezer** [pbeshai/use-query-params#113]
```js
const [filtersState, setFiltersState] = useQueryParams(
        config.reduce(
            (result, { name, paramType = StringParam }) => (name ? { ...result, [name]: paramType } : result),
            {}
        )
    );
```

if config at first look like:

```js
[{
name: 'testName'
}]
```
after some time:

```js
[{
name: 'testName'
},{
name: 'testNameNew'
}]
```

app crush with this error
<img width="1792" alt="Screenshot 2020-06-29 at 14 45 43" src="https://user-images.githubusercontent.com/19321990/86001284-5ae20f00-ba17-11ea-92a5-5ef4e82d3fad.png">

**Comment by pbeshai** [comment]
Fixed by #114, out in v1.1.5. Thank you!
