### ISSUE TITLE
Functional updates broken when value needs to be encoded

### ISSUE THREAD

**Issue by codelizrd** [pbeshai/use-query-params#116]
Hi,

Looking at the code in:
- useQueryParams.ts: setQuery callback
- useQueryParam.ts: setValue callback

When updating directly with a value, the value is first encoded before invoking setLocation. 

But then the value is a function (for functional updates), the function is invoked with the current value but the returned value is never encoded before invoking setLocation. Hence, JsonParam encoded values are given to history.push({query}) - which does not work.

``` // allow functional updates #26
      if (typeof newValue === 'function') {
        // get latest decoded value to pass as a fresh arg to the setter fn
        const latestValue = getLatestDecodedValue(
          getLocation(),
          name,
          paramConfig,
          paramConfigRef,
          encodedValueCacheRef,
          decodedValueCacheRef
        );
        decodedValueCacheRef.current = latestValue; // keep cache in sync

        newEncodedValue = (newValue as Function)(latestValue); // <== **VALUE IS RAW, NOT ENCODED**
      } else {
        newEncodedValue = paramConfig.encode(newValue);
      }

      // update the URL
      setLocation({ [name]: newEncodedValue }, updateType);```

**Comment by pbeshai** [comment]
Fixed in v1.1.6
