### ISSUE TITLE
Passing new paramConfig ref to hooks results in new setter ref on every update

### ISSUE THREAD

**Issue by austin-payne** [pbeshai/use-query-params#121]
### Summary

The `useQueryParam` and `useQueryParams` hooks return setters created with `useCallback` and a dependency on the `paramConfig` or `paramConfigMap` passed in, respectively. This is fine when using passing in constant values such as `StringParam` for the param config, for example:

```ts
const [...] = useQueryParam('name', StringParam);
```

But returns new setter reference values when the param config changes, on every call to the hook:

```ts
// withDefault always returns an object with a new reference value
const [value, setValue] = useQueryParam('name', withDefault(StringParam, 'default'));
```

```ts
// this paramConfigMap is always a new object, therefore a new reference value
const [values, setValues] = useQueryParam({
    name: withDefault(StringParam, 'default')
});
```

In these examples, every time the component receives an update, a new setter function will be returned. This causes issues in scenarios where the setter function is used as a dependency of a useEffect that calls the setter within the same component, or other potential scenarios:

```ts
const someValueFromSomething: string = 'test';

const [value, setValue] = useQueryParam('name', withDefault(StringParam, 'default'));

// This results in an infinite render loop due to setValue having a new reference value on every component update
useEffect(() => {
    setValue(setValueFromSomething);
}, [someValueFromSomething, setValue]);
```

### Conclusion

The hooks should be able to handle updated reference values of the param configs without returning new setter functions. This is an awesome library 😄, just think it could return the setter functions in a slightly safer way to be more user friendly (imo dispatch functions from hooks should never get new reference values, even if it increases the complexity of the hook behind the scenes). I'm happy to make a followup PR sometime in the future regarding this; and if I'm just totally misusing this library feel free to disregard 😅

**Comment by pbeshai** [comment]
Hi @austin-payne, thanks for your detailed issue. If you look through the code, you'll see that there is special care taken to handle this situation. However, the problem here is that you're creating a new parameter type each render as a result of calling withDefault(). Viable solutions include:

1. Define `const MyStringParam = withDefault(StringParam, 'default')` outside of your component
2. Wrap your call to withDefault with useMemo e.g. `useQueryParams({ name: useMemo(() => withDefault(StringParam 'default'), []) })`
3. Update the withDefault function to handle the memoizing of values. This could happen in the library or in user code. I think it's a bit weird for withDefault to do this in the library.

I personally find going with option 1 works in practice.

**Comment by austin-payne** [comment]
Hey @pbeshai, no problem and thanks for the reply! 😄

I should've been more clear about where I'm coming from with this issue, it was pretty late when I made it haha. I understand why this behavior was occurring, but just don't see a need for setQuery to end up with a new reference value. By adding another useRef within the hook to contain the deps used by the function, which can then be grabbed on demand when the function is called, the same behavior can be achieved but with an empty useCallback deps array. In my opinion, functions returned by hooks (especially from libraries, and even hooks locally defined in one project that are widely used within the project) should always have constant reference values. React itself does this with `useState`, and I've seen some other libraries follow this "rule" as well. The main downside is just the extra code required to accomplish this. But it's worth it in libraries to avoid potential headaches, improve performance, and be slightly more inclusive of newer developers (or even experienced developers new to hooks). It's one of those things that I wish was explored a bit in the official react docs 😞 

Regardless, I think that your suggestions 1 (when possible) or 2 (when you need some data within the component to create the parameter type) are both worth doing anyway because of how the internal caching is handled. And I agree suggestion 3 would be a bit weird.

As a side note, I love how easy it was to dig into the code, makes me love this library even more. I've got a PR coming soon to resolve this ticket if you don't mind 🙂

**Comment by pbeshai** [comment]
Sorry for the delay, was waiting for the other mentioned PR in #123 which hasn't been posted. This is now up in v1.1.7
