### ISSUE TITLE
Allow specifying default update type in hook args

### ISSUE THREAD

**Issue by austin-payne** [pbeshai/use-query-params#123]
### Summary

Currently, updateType is an optional arg of the setter returned by useQueryParam(s), and defaulted internally to `pushIn`. I'd like to be able to pass a default update type as an arg to the hook, rather than the setter. This would simplify the code in the following scenario:

```ts
const [state, setState] = useState('asdf');

// passing setState as a prop to some other component
```

```ts
// now want to back the same state by a query parameter with useQueryParam
const [state, setState] = useQueryParam('state', withDefault(StringParam, 'asdf'));

// but want the setter to replace, rather than pushIn
const setStateReplace = useCallback((value: string) => setState(value, 'replace'), [setState]);

// can now pass setStateReplace to the same component
```

```ts
const [state, setState] = useQueryParam('state', withDefault(StringParam, 'asdf'), 'replace');

// can pass setState without having to wrap setter
```

**Comment by austin-payne** [comment]
@pbeshai I have a PR ready for this after #122 since it's based on that branch 🙂

**Comment by pbeshai** [comment]
Thank you, please feel free to open it

**Comment by trevorr** [comment]
This would be very convenient. Are you still planning to open a PR @austin-payne?

**Comment by pbeshai** [comment]
Hi there, this has been added in v2.0.0-rc.0  via the `updateType` option. Give it a try and let me know if you run into issues. See the [changelog](https://github.com/pbeshai/use-query-params/blob/master/packages/use-query-params/CHANGELOG.md#migrating-from-v1) for details.
