### ISSUE TITLE
Using without a router

### ISSUE THREAD

**Issue by liegeandlief** [pbeshai/use-query-params#124]
How would I go about using this project without a router? I have tried passing the history prop to the provider with a history object created from the `history` npm package, but the TypeScript types are incompatible:

```
Type 'BrowserHistory<State>' is not assignable to type 'PushReplaceHistory'.
  Types of property 'location' are incompatible.
    Type 'Location<State>' is missing the following properties from type 'Location': ancestorOrigins, host, hostname, href, and 6 more.ts(2322)
```

**Comment by pbeshai** [comment]
I suppose the default `Location` type could be simplified to a duck-type that matched just what we need... but you could also just try casting the type to make it work? e.g. something like:

```ts
type History<State> = BrowserHistory<State> & { location: Location }
```

[typescript playground example](https://www.typescriptlang.org/play?#code/C4TwDgpgBA6gTgewHYHMAyCDGBDYBLZKAXigG8BfAbgChrRIoAhRAdwGcI4AJPN4BOCAA8AFQB8xMtShQ+uCAC4oImjIA2WXASRL4ydJvzIa5WvWgAxPAA8IAEx58Bw8ZOYJ2nR-0GiJAMjIoDRwjHSgMUO0oKlo8JGBOADNsTGgABQBXNgALACUIMDVUiG9nKXVDbQB+JUitYygAeiaoAFtsAGtoPGAoBDAw7DVZBCgWaBwkKAAjaBnUzpZsODs2KEwENrAtGbVoAApsOzt7KHioAEYAOhuAJgBKalNqfb6Z1g5uXh8QJXdPN8nL4KBISBQoNh1tgkCAaG8oEkbPYyoIlFZbA4fs4hKDJBCoZDYTRqElMkhMGEoIk+EkkAcwNl8oVimlUX8oFlcgUiiV2Q8pC8acA6QcPh4vvyaMLRUjMVLaNQgA)

**Comment by chozzz** [comment]
If you have a `history` object, you can just wrap it with `QueryParamProvider` with `history` attribute. Here's how I do it;

```
import { createMemoryHistory, createBrowserHistory } from 'history';

const history = isSSR ? createMemoryHistory() : createBrowserHistory(),
  pushReplaceHistory: PushReplaceHistory = {
    push: (location: Location): void => {
      history.push(location);
    },
    replace: (location: Location): void => {
      history.replace(location);
    },
    location: isSSR ? ((history.location as unknown) as Location) : window.location,
  };
  ReactDOM.render(
    <Provider store={store}>
      <Router history={history}>
        <BrowserRouter>
          <QueryParamProvider history={pushReplaceHistory}>
            <App />
          </QueryParamProvider>
        </BrowserRouter>
      </Router>
    </Provider>,
    document.getElementById('app')
  );
```
