### ISSUE TITLE
query-string dependency triggers runtime error

### ISSUE THREAD

**Issue by bstro** [pbeshai/use-query-params#132]
I am working in a monorepo, with a front-end built with `create-react-app`. I am attempting to use this `use-query-params` hook in my project, but I keep getting the following runtime error:

![image](https://user-images.githubusercontent.com/627290/97070077-38f23680-158a-11eb-94a4-316f6911493b.png)

I followed the instructions of this project's `readme.md` and installed the latest `query-params` as a peer dependency, though I am not actually using `query-string` in my project (there are no entries for it in my `package.json` other than the peer dependency I just added), so I went looking in the `yarn.lock` file. Sure enough, there is an entry for `query-string@^4.1.0` which is a transitive dependency of a couple other libraries.

![image](https://user-images.githubusercontent.com/627290/97070110-925a6580-158a-11eb-9ee2-ac0392f5a6be.png)

I'm a bit at a loss here and don't understand why `use-query-params` can only see this old version, despite the fact that I have the latest listed as a peer dependency:

![image](https://user-images.githubusercontent.com/627290/97070144-eb29fe00-158a-11eb-97f2-0fd2204d8a51.png)

This hook looks great and I really hope I can make it work!

**Comment by bstro** [comment]
nvm, seems like I misunderstood the line in the `README.md` that states: `Note: There is a peer dependency on query-string.` I moved it from my peer dependencies to my dependencies and everything seems to work. 👍

**Comment by pbeshai** [comment]
Ah yea, sorry for the confusion, but glad you got it working. Thank you for sharing your experience here, hopefully it helps others
