### ISSUE TITLE
Array of objects

### ISSUE THREAD

**Issue by Keysi77** [pbeshai/use-query-params#133]
It would be nice if this lib support Array of object shape
Simple example:
```
const [query, setQuery] = useQueryParams({
		activeKeys: ArrayOfObjects
	})
```
```
setQuery({ activeKeys:[{
activeTab: 5,
visible: true
key: 5
}] })
```
And u can acces to this like query.activeKeys[_yourIndex_].activeTab
For example if u have multiple TABS sections in Collapses and you want to set default values for active tabs and collapses

**Comment by pbeshai** [comment]
You can always use JsonParam for this or just make your own param type that does what you want, you just need to create an encode/decode functions - example:

```js
import {
  encodeDelimitedArray,
  decodeDelimitedArray
} from 'serialize-query-params';

/** Uses a comma to delimit entries. e.g. ['a', 'b'] => qp?=a,b */
const CommaArrayParam = {
  encode: (array: string[] | null | undefined): string | undefined => 
    encodeDelimitedArray(array, ','),

  decode: (arrayStr: string | string[] | null | undefined): string[] | undefined => 
    decodeDelimitedArray(arrayStr, ',')
};
```

You can base it off the existing params if you find it helpful, all of their encode/decode functions are exported: 
* https://github.com/pbeshai/serialize-query-params/blob/master/src/params.ts
* https://github.com/pbeshai/serialize-query-params/blob/master/src/serialize.ts
