### ISSUE TITLE
When using ArrayParam type, e.g. Facebook will parse the url and remove all elements but the last

### ISSUE THREAD

**Issue by m3h0w** [pbeshai/use-query-params#137]
When using the Array type, multiple values in the query string are represented by the same string. E.g.: `https://covid19.pink/infection-trajectories?c=Netherlands&c=Poland&c=Sweden&c=Denmark&c=Germany&log_scale=0&per_capita=0`. The array of strings is represented by multiple strings of the same name "c".

When that link is pasted into Facebook, their algorithm parses the URL to attach fbclid to the end of it for tracking and in the process it only recognizes last element of the array. This is the resulting string: `https://covid19.pink/infection-trajectories?c=Germany&log_scale=0&per_capita=0&fbclid=IwAR0p19MIvHAbIV7jyjz9UG_hDLO9sHoxrNm-aXgh5ZuZl_0o5zmjx9xA1A8`

I assume this will be easy to blame on Facebook but I thought that it's possible that the way you're representing the array as the same query parameter name might be defying some general standards. I don't know much about those myself but it seemed quite odd that something as obvious as pasting the link on Facebook (I just spend an entire day implementing this feature using use-query-params library just to get that to work) doesn't work. 

The simplest solution I can think of is to have some kind of system of naming the elements in the array, like c*0, c*1, c*2, ..., etc.

**Comment by pbeshai** [comment]
You can control the array style via the stringifyOptions prop which should map to the query-string stringify function. In particular arrayFormat may be of interest to you: https://github.com/sindresorhus/query-string#arrayformat-1

Unfortunately I think it is only set up to work for encoding not for parsing, so we may need a PR to update the parsing code to also take in the options.

**Comment by pbeshai** [comment]
You can also just use the DelimitedArrayParam instead if that suits you

**Comment by m3h0w** [comment]
Thanks! DelimitedArrayParam works nicely. Any reason not to suggest that as the default given the unexpected behavior of the ArrayParam? Is the ArrayParam preferred in some cases?

**Comment by m3h0w** [comment]
> You can control the array style via the stringifyOptions prop which should map to the query-string stringify function. In particular arrayFormat may be of interest to you: https://github.com/sindresorhus/query-string#arrayformat-1
> 
> Unfortunately I think it is only set up to work for encoding not for parsing, so we may need a PR to update the parsing code to also take in the options.

I'm not sure I understand the difference between encoding and parsing in this case

**Comment by pbeshai** [comment]
I did have DelimitedArrayParam as the default and it's what I like to use if I can since it makes the URL shorter, but reddit denizens got mad about it since technically there already is array support for params by those other styles, so I just renamed ArrayParam to DelimitedArrayParam and made ArrayParam just rely on the query-string logic.

Re: encode/parse sorry these words are not clear. I mean convert from foo: [a,b,c] -> ?foo=a&foo=b&foo=c as "encode" or "stringify" and parse/decode to be go from ?foo=a&foo=b&foo=c to foo: [a,b,c]. I lazily added stringifyOptions and it only goes to the encode step, but I think query-string would require it also to be set for decoding `foo[]=a&foo[]=b&foo[]=c` or `foo[0]=a&foo[1]=b&foo[2]=c`.

**Comment by m3h0w** [comment]
Okay, I think now I understand. It does make sense to have the `stringifyOptions` available I guess for cases potentially not handled by the Param types.

> ...but reddit denizens got mad about it since technically there already is array support for params by those other styles,

It was much more intuitive out-of-the-box for me to just follow the pattern of replacing the Param type when I want a different way of encoding the parameters than I think it would be to just for this specific case have to find the `stringifyOptions`.

What would you say to having a short mention of the potential problems of the default ArrayParam behavior and mentioning explicitly DelimitedArrayParam as an alternative for someone who doesn't notice it there at the end of the table - like me? :)
