### ISSUE TITLE
Broken link in README file

### ISSUE THREAD

**Issue by AGarcia-Clarity** [pbeshai/use-query-params#143]
README.MD link points to a broken link with the wrong serialization utility file

**Current**
> You can define your own params if the ones shipped with this package don't work for you. There are included serialization utility functions _https://github.com/pbeshai/use-query-params/blob/master/src/serialize.ts_ to make this easier, but you can use whatever you like.

**Update to**
> _**https://github.com/pbeshai/serialize-query-params/blob/master/src/serialize.ts**_

Thank you!

**Comment by pbeshai** [comment]
Thank you! Fixed in #144, feel free to edit it and make a PR in the future
