### ISSUE TITLE
Feature Request: Update Query Params without triggering re-render

### ISSUE THREAD

**Issue by ingvaldlorentzen** [pbeshai/use-query-params#145]
Would love a option to be able to update the query params without triggering a re-render.

I'm guessing this should be possible to achieve by manipulating the `location` object directly, vs. doing it with the router in the QueryParamProvider. 

This could be added either as an additional optional parameter to the `set` functions, or as another `updateType`

I'm gonna look into making a PR for this, but any guidance, tips or design input would be greatly

**Comment by pbeshai** [comment]
If you manipulate the URL outside of your router's history object knowing, then back/forward won't work properly. Generally speaking, extra re-renders aren't problematic and can often be mitigated by React.memo(). The library itself does not control rendering at all, it just updates the URL via the router and the router is what triggers the re-render on the history changing.

However, in the next version, I would like to make it easier to have components only re-render when the portions of the URL they are interested in change, but will require some more thought.

**Comment by ingvaldlorentzen** [comment]
Thanks for the feedback!

A version where only the components listening to they respective query param get re-rendered would be awesome! Completely understand that that is a pretty big undertaking though, that definitely requires some thought.

As to the back button not working correctly, thanks for the heads up, I'll be sure to double-check that so I get the behaviour the way I want it when using the workaround. 

Thanks for an amazing package!

**Comment by pbeshai** [comment]
FYI a way to get the behavior of only what you want causing a re-render is to use the HOC version withQueryParams.. something like:

```js
const MyComponent = ({ x, q, filters }) => { ... };

export default withQueryParams({
  x: NumberParam,
  q: StringParam,
  filters: withDefault(ArrayParam, []),
}, React.memo(MyComponent));
```

Or just wrapping in an outer component that is aware of the URL:


```js
const MyComponent = ({ x, q, filters }) => { ... };
const MemoMyComponent = React.memo(MyComponent);

const MyComponentWrapper = ({ ... }) => {
  const [{ x, q, filters }, setQuery] = useQueryParams({
    x: NumberParam,
    q: StringParam,
    filters: withDefault(ArrayParam, []),
  });
  
  return <MemoMyComponent x={x} q={q} filters={filters} />
}
```

**Comment by priley86** [comment]
I still seem to see `MyComponent` remounting after `setQuery` is called with `push` mode (default), even after wrapping like this with `React.memo`. Is this intended by this library at the moment? It would be nice to alleviate this some way. 

Also tried alleviating this by changing the QueryParamProvider, but with no effect either...

Provider:
```
    <Router history={history}>
      <ApolloProvider client={client}>
        <QueryParamProvider
          ReactRouterRoute={Route}
          history={(history as unknown) as PushReplaceHistory}
          location={(history.location as unknown) as Location}>
          <App />
        </QueryParamProvider>
      </ApolloProvider>
    </Router>,
``` 

For history, I am using the `createBrowserHistory` initializer from the npm `history` module:
```
import { createBrowserHistory } from 'history';
export default createBrowserHistory();
```

**Comment by pbeshai** [comment]
If you can put together a codesandbox demonstrating the issue I may be able to help diagnose it
