### ISSUE TITLE
Add abilitilty to use empty strings instead of undefined

### ISSUE THREAD

**Issue by AntwanSherif** [pbeshai/use-query-params#147]
First off, I would like to thank you for saving my time handling query parameters.

I have an issue though with default empty values to undefined. I would like to be able to somehow control that behavior for the following use cases:

1. Some component (for example: input fields, selects, dropdowns, etc.) don't accept undefined as a value. The default is an empty string.
2. The URL would be nicer if empty string values are removed rather than explicitly set it to undefined to be removed
`www.my-website.com` is much nicer than `www.my-website.com/sort=` 
where the current selection is an empty string

**Comment by pbeshai** [comment]
Hi there, glad this library has been helpful for you. In the next version, I'd like to make it easier for people to be able to say "default params are removed from the URL", and then you'd be able to accomplish this by saying the default value is `""`. But for now, you can get what you want by creating your own string parameter:

```js
import {
  useQueryParam,
  encodeString,
  decodeString
} from "use-query-params";

const MyStringParam = {
  encode: (str) => {
    // by replacing these values with undefined, they are removed from the URL
    if (str === "" || str == null) return undefined;

    return encodeString(str);
  },
  decode: (urlStr) => {
    const decoded = decodeString(urlStr);

    // coerce nully values to empty string for usage in app
    if (decoded == null) return "";
    return decoded;
  }
};

export default function App() {
  const [myStr, setMyStr] = useQueryParam("myStr", MyStringParam);
  // ...
}
```

[Codesandbox example](https://codesandbox.io/s/use-query-params-empty-string-y13ez?file=/src/App.js)

**Comment by AntwanSherif** [comment]
@pbeshai Thanks for the quick response. I really appreciate it.
