### ISSUE TITLE
CommaArrayParam example doesn't work for me

### ISSUE THREAD

**Issue by Deliaz** [pbeshai/use-query-params#149]
I am trying to store a date range array using the example with `CommaArrayParam`. 

```javascript
/** Uses a comma to delimit entries. e.g. ['a', 'b'] => qp?=a,b */
const CommaArrayParam = {
  encode: (array: string[] | null | undefined) =>
    encodeDelimitedArray(array, ','),

  decode: (arrayStr: string | string[] | null | undefined) =>
    decodeDelimitedArray(arrayStr, ',')
};
```

```js
useQueryParams({
    ...
    dateRange: withDefault(CommaArrayParam, []),
})
```

However, when passing array `[2020-08-01, 2020-10-01]`, the URL still looks like `?dateRange=2020-08-01%2C2020-10-01`. 
Meanwhile `DelimitedArrayParam` works as expected. 

What do I miss? 

Package version: 1.2.0

**Comment by pbeshai** [comment]
Comma is a special character in URLs so it is typically escaped (which is why it is not the default in DelimitedArrayParam). If you want to configure some common JSON-y characters to not be escaped since they actually do work in most browsers, you can use `transformSearchStringJsonSafe` as a stringify option when setting up use-query-params:

```js
import * as React from 'react'
import ReactDOM from 'react-dom'
import { BrowserRouter as Router, Route } from 'react-router-dom'
import {
  QueryParamProvider,
  transformSearchStringJsonSafe,
} from 'use-query-params'

// use-query-params config
const stringifyOptions = {
  transformSearchString: transformSearchStringJsonSafe,
}

ReactDOM.render(
  <Router>
    <QueryParamProvider
      ReactRouterRoute={Route}
      stringifyOptions={stringifyOptions}
    >
      <App />
    </QueryParamProvider>
  </Router>
)
```
