### ISSUE TITLE
Special symbol like '+', '-' is not getting by Any of the param types

### ISSUE THREAD

**Issue by mitul-srashtasoft** [pbeshai/use-query-params#155]
Special symbol like '+', '-' is not getting by Any of the param types

**Comment by pbeshai** [comment]
Sorry, I don't understand what you mean. Can you elaborate or create a codesandbox demonstrating the issue? Since we use query-string for encoding to the URL in the end, they should all work.

```
> const qs = require('query-string')
> qs.stringify({ foo: 'a + b + c - d' })
'foo=a%20%2B%20b%20%2B%20c%20-%20d'
```
