### ISSUE TITLE
Params not reset on route change when using React Router's HashRouter

### ISSUE THREAD

**Issue by SuaYoo** [pbeshai/use-query-params#16]
Search params are not reset on navigation when using React Router's [`HashRouter`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/HashRouter.md).

react-router: 5.0.0  
react-router-dom: 5.0.0  
use-query-params: 0.3.2

Reproduced here: <https://codesandbox.io/s/tender-williamson-qtqcr>
1. Click "to bar" button. Observe that the preview Browser tab URL updates to `https://qtqcr.codesandbox.io/?foo=bar`.
2. Click "Link two" link.  Preview URL is now `https://qtqcr.codesandbox.io/?foo=bar#/two`, when it should be `https://qtqcr.codesandbox.io/#/two`.

If you comment out the `App` on line 51, which doesn't use `HashRouter`, the params in the URL update as expected.

**Comment by pbeshai** [comment]
You need to provide **QueryParamProvider** (see Installation section of the README)

e.g.,

```js
ReactDOM.render(
  <BrowserRouter>
    <QueryParamProvider ReactRouterRoute={Route}>
      <App />
    </QueryParamProvider>
  </BrowserRouter>,
  rootElement
);
```
