### ISSUE TITLE
"Cannot find module 'query-string/package.json'" runtime error

### ISSUE THREAD

**Issue by huwmartin** [pbeshai/use-query-params#163]
Hi, love this library - I think it will solve a lot of problems for us on the project I'm currently working on. Trying to get it set up and running up against an issue in development where I'm seeing the following error at runtime

```
client.js:8866 Uncaught Error: Cannot find module 'query-string/package.json'
    at webpackMissingModule (client.js:8866)
    at Object../node_modules/query-string/package.json (client.js:8866)
    at __webpack_require__ (client.js:64)
    at eval (index.js?d603:12)
    at Module../node_modules/serialize-query-params/esm/index.js (client.js:14306)
    at __webpack_require__ (client.js:64)
    at eval (index.js?4d98:1)
    at Module../node_modules/use-query-params/esm/index.js (client.js:14774)
    at __webpack_require__ (client.js:64)
    at eval (client.tsx:25)
```

I have the following installed

```
"use-query-params": "^1.2.2",
"query-string": "^6.0.0",
```

Obviously I figure this is happening here https://github.com/pbeshai/use-query-params/blob/452aecddd960ef311a16fd7621fd968c43e0bd83/packages/serialize-query-params/src/index.ts#L67 I would be gracious to hear if there is anything obvious I'm missing with my setup :)

**Comment by pbeshai** [comment]
interesting. I think that helper code has caused more headaches than it's worth. I'll just remove it and republish. not sure what would've removed that file from existing but maybe some combination of your build system + package manager

**Comment by pbeshai** [comment]
ok I've updated serialize-query-params to not have that code anymore in v1.3.4. If you reinstall use-query-params it should get the latest

**Comment by joepio** [comment]
I think I'm having a similar / the same issue with snowpack. I didn't have any problems, until I split up my own project with Lerna. 

Anyways, this is my error at runtime:

```
SyntaxError: import not found: parseUrl
https://localhost:8080/dist/pkg/serialize-query-params.v1.3.4.js [:1:20] 
```

Seems to be originating from:

```
import { stringify, parseUrl, parse } from '/dist/pkg/query-string.v4.3.4.js';
```

> ok I've updated serialize-query-params to not have that code anymore in v1.3.4. If you reinstall use-query-params it should get the latest
Great, thanks! Could you also publish that version to npm? Latest over there is 1.2.2, and for some reason I can't use your specific commit as a dependency.

**Comment by pbeshai** [comment]
https://www.npmjs.com/package/serialize-query-params v1.3.4 is up. You may need to npm remove then re-install use-query-params to get the latest serialize-query-params

**Comment by joepio** [comment]
Thanks for the very quick reply! You're right, I didn't understand you correctly. 

Issue is still there though, so I guess my issue is not related.
