### ISSUE TITLE
let consumer pass their own query string implementation

### ISSUE THREAD

**Issue by y-nk** [pbeshai/use-query-params#171]
peer dependency on query-string is a bit of a constraint ; lots of people use different libraries and dont want to carry 2 libraries doing the same thing. I'm personally using `qs` which is quite more popular/downloaded and support some cases which are not supported by query-string.

it'd be probably beneficial to have a `qsParser` object which we can set, of type:

```
interface QueryStringParser {
  parse(str: string): Object,
  stringify(obj: any): string,
}
```

**Comment by pbeshai** [comment]
I do like this idea. would be nice not to require query-string (and also to allow people to use URLSearchParams if they so choose)

**Comment by pbeshai** [comment]
Hi there, this has been added to v2.0.0-rc.0. See the [changelog](https://github.com/pbeshai/use-query-params/blob/master/packages/use-query-params/CHANGELOG.md#migrating-from-v1) for details.
