### ISSUE TITLE
use-query-params with query-string ^7 loads parseUrl() as an Object in production

### ISSUE THREAD

**Issue by BirdTho** [pbeshai/use-query-params#178]
I have this use-query-params library, and in local React development it works fine, but when I deploy on production then do anything that would change the URL, such as using a set*() method on a useQueryParam() hook I immediately get issues in a more production scenario.

In updateLocation.ts/js (and I'm using Typescript) there's a call to parseUrl() in updateLocation() which registers as an Object, but is being called like a function. What might cause this sort of hiccup?

```var href = parseUrl(location.href || '').url + search;```

**Comment by siddharth329** [comment]
I too am having the same problem
![image](https://user-images.githubusercontent.com/70111559/127440438-27cc8e3a-800a-4231-8bf4-e29754ccc019.png)

**Comment by daisybaicai** [comment]
you should install query-string and use-query-params, i solve this problem when i install query-string

**Comment by hugomartinet** [comment]
Thanks for the tip!
Maybe `query-string` should be listed in the dependencies?
