### ISSUE TITLE
Do not support ConnectionRouter

### ISSUE THREAD

**Issue by ChenXiaoTemp** [pbeshai/use-query-params#19]
Hi, Error occurs when put QueryParamProvider in ConnectionRouter like following:

<img width="946" alt="屏幕快照 2019-06-06 下午7 03 44" src="https://user-images.githubusercontent.com/5827720/59028319-eb3e3680-888d-11e9-9003-2d5f8bfa26ad.png">

**Comment by pbeshai** [comment]
Sorry, I don't know what ConnectionRouter is.. can you provide some more code of where you used QueryParamProvider?

**Comment by thexpand** [comment]
I think that's https://github.com/supasate/connected-react-router
A Redux binding for React Router.

**Comment by leonelgalan** [comment]
What if you share the history between `ConnectedRouter` and `QueryParamProvider`:

```jsx
    <ConnectedRouter history={history}>
      <QueryParamProvider history={history}>
```

This seems to work for me, but I'm unsure of your use case.
