### ISSUE TITLE
URL path getting decoded when calling setQuery

### ISSUE THREAD

**Issue by i11ltech** [pbeshai/use-query-params#192]
When calling setQuery the URL path gets decoded which breaks the API call because of the special char.
http://localhost:3000/articles/abc%5B0%5D?x=3 , gets converted to
http://localhost:3000/articles/abc[0]?x=3

Example:
`
const [query, setQuery] = useQueryParams({
    x: NumberParam,
.....
  });

setQuery( { x: 22 ,... )
`

When setQuery gets called the URL gets updated with decoded path, when stepping through the code the line where the conversion happens is in useQueryParams.js 
line 115: `deps.setLocation(encodedChanges, updateType)`

It looks like the location object is decoding the path. There are functions to encode the params but not the path.
Please advice.

**Comment by pbeshai** [comment]
I believe this has been fixed in v2.0.0-rc.0. Let me know if you have any issues. See the [changelog](https://github.com/pbeshai/use-query-params/blob/master/packages/use-query-params/CHANGELOG.md#migrating-from-v1) for migration info.
