### ISSUE TITLE
Error when upgrading `react-router-dom` to version 6: "A <Route> is only ever to be used as the child of <Routes>"

### ISSUE THREAD

**Issue by Avivhdr** [pbeshai/use-query-params#195]
Hi 👋🏼

https://codesandbox.io/s/react-router-basic-forked-m6w00?file=/example.js

In the above Codesandbox, there is a simple react-router (v6) example wrapped with `<QueryParamProvider />`.
Code:
```
<QueryParamProvider ReactRouterRoute={Route}>
  <Routes>
    <Route exact path="/" element={<Home />} />
    <Route path="/about" element={<About />} />
    <Route path="/dashboard" element={<Dashboard />} />
  </Routes>
</QueryParamProvider>
```
The code results in the following Error:
```
Error
A <Route> is only ever to be used as the child of <Routes> element, never rendered directly. 
Please wrap your <Route> in a <Routes>.
```

When commenting out the `QueryParamProvider` wrapper, the app renders.

`use-query-params` - v1.2.3
`react-router-dom` - v6.0.2

**Comment by pbeshai** [comment]
Please follow these instructions for now https://github.com/pbeshai/use-query-params/issues/108#issuecomment-785209454

**Comment by Avivhdr** [comment]
Thank you!
I close this ticket.
