### ISSUE TITLE
useMemo should not be used as a semantic guarantee

### ISSUE THREAD

**Issue by dylansteele8** [pbeshai/use-query-params#20]
I really like the change to memoize the decoded values to maintain referential equality! However, reading through [the React docs about `useMemo`](https://reactjs.org/docs/hooks-reference.html#usememo), it seems as if code should not rely on `useMemo` for referential equality:

> **You may rely on useMemo as a performance optimization, not as a semantic guarantee.** In the future, React may choose to “forget” some previously memoized values and recalculate them on next render, e.g. to free memory for offscreen components. Write your code so that it still works without `useMemo` — and then add it to optimize performance.

Therefore, I would be concerned that the below code might break at some point.

https://github.com/pbeshai/use-query-params/blob/c9b4af2695914fe8564eb23179d9da2e3d872c2f/src/useQueryParam.ts#L46

https://github.com/pbeshai/use-query-params/blob/c9b4af2695914fe8564eb23179d9da2e3d872c2f/src/useQueryParams.ts#L39

It would be great to keep this feature of returning the same object if the query parameters have not changed. I frequently use the result of `useQueryParam(s)` in a `useEffect` hook that I only want to run when the query parameters have actually changed. Without this memoization, the `useEffect` could become a "runaway" if it causes the component to re-render and call `useEffect` again.

This isn't a critical issue since it seems to be working fine for now. However, I think it's worth looking into potential alternatives that provide the semantic guarantee.

**Comment by pbeshai** [comment]
I don't think this interaction between useMemo and useEffect needs to be avoided. You have something so critical in your useEffects that you can't handle it running more than once ever? It should be pretty rare that React ever drops the memoized value unexpectedly. Maybe you can provide a more clear example of why this would be problematic for you. I believe the only alternative is to do the memoizing through a different mechanism than useMemo, which I'd prefer to avoid for simplicity.

**Comment by dylansteele8** [comment]
Hey, thanks for the quick response! I totally agree with you that it should be rare for React to drop the memoized value. My concern is that React says not to rely on `useMemo`. Based "write your code so that it still works without `useMemo`", I think it is worth exploring other mechanisms at some point because the code doesn't always work without it.

To clarify about my `useEffect`, it's totally fine if it runs twice (or even more). However, it's an issue for my `useEffect` (and probably anyone's `useEffect`) if it runs in an indefinite loop. I wrote [a quick example](https://codesandbox.io/s/play-use-query-params-408qd?fontsize=14&initialpath=%2F%3Fx%3D0.5) to showcase what I mean by running in an indefinite loop. It relies on the component having some state that gets updated whenever the query updates. I admit it is an extreme case of `useMemo` not working, but it is a realistic case if `useMemo` is not used at all by `useQueryParams`. Let me know if the example doesn't make sense or if I wrote something fishy that may be more of a concern.

**Comment by jsejcksn** [comment]
Use a `ref`: https://github.com/facebook/react/issues/15278

(Check out examples of `usePrevious` and other community hooks for comparison of dependency values.)

**Comment by pbeshai** [comment]
Although I still haven't run into any issues around this, I think this has been addressed with recent changes to useQueryParams: https://github.com/pbeshai/use-query-params/blob/master/src/useQueryParams.ts#L69

useQueryParam is likely still affected: https://github.com/pbeshai/use-query-params/blob/master/src/useQueryParam.ts#L50
