### ISSUE TITLE
DelimitedArrayParam gets URIencoded

### ISSUE THREAD

**Issue by alexeygolev** [pbeshai/use-query-params#23]
[Here](https://codesandbox.io/s/prod-darkness-y44uc) is an example. 

The url bar in the preview window show the correct value for parameter `x`. In reality (you can check it by clicking the "Open in new window" button next to the url bar) the params are uri encoded resulting in `?x=1%7C2` instead of `?x=1|2`.

"query-string" library doesn't do it with `arrayFormat="comma"`. The only reason that I can see this happening is that the `stringify` function is called _after_ the encoding happens so "query-string" treats it as a string and uri encodes it.

I'd assume the way to fix it is to set `encode` to false when calling the stringify. I looked around for possible settings that I can use on a higher level (as the "query-string" level is not accessible) but couldn't find anything.

Is there anything that can be done to prevent this from happening?

**Comment by pbeshai** [comment]
Thanks for bringing this up! Right now I just call [stringify with no options passed](https://github.com/pbeshai/serialize-query-params/blob/master/src/updateLocation.ts#L12)... could be worth exposing the options argument with perhaps a top-level config at the QueryParamsProvider level. I'm not sure we could trigger it on a per param level.
