### ISSUE TITLE
Calling setQuery changes references to query params which are either objects or arrays

### ISSUE THREAD

**Issue by RomanTokar** [pbeshai/use-query-params#230]
## Actual behavior

```javascript
import { useEffect } from "react";
import { useQueryParams, withDefault, JsonParam } from "use-query-params";

export default function App() {
  const [query, setQuery] = useQueryParams({
    json: withDefault(JsonParam, {})
  });
  console.log(JSON.stringify(query));

  useEffect(() => {
    setQuery((prev) => ({ ...prev}));
  }, []);

  useEffect(() => {
    console.log("here");
  }, [query.json]);

  return null;
}
```

### Console

<img width="159" alt="image" src="https://user-images.githubusercontent.com/49822676/185364654-0db64b3a-e419-44ab-a35e-fb0cbe571fad.png">

https://codesandbox.io/s/use-query-params-jsonparam-issue-737tn4?file=/src/App.js

As you can see, whenever we call `setQuery` and change our params, a reference to `query.json` is changed and the second `useEffect` is called.

## Expected behavior

I assume that it should work the same as behavior of the `useState` hook

```javascript
import { useEffect, useState } from "react";

export default function App() {
  const [query, setQuery] = useState({
    json: {}
  });
  console.log(JSON.stringify(query));

  useEffect(() => {
    setQuery((prev) => ({ ...prev}));
  }, []);

  useEffect(() => {
    console.log("here");
  }, [query.json]);

  return null;
}
```

### Console

<img width="160" alt="image" src="https://user-images.githubusercontent.com/49822676/185365826-15670123-74e8-4ee9-9993-cb18731ae3d9.png">

> And I would like to add that every render a reference to `query` object is being changed as well.

**Comment by pbeshai** [comment]
The issue is you're creating a new param each render by calling withDefault so useQueryParams doesn't know it can keep the old value. If you define your parameter type once, it will work as expected:

```js

const MyParam = withDefault(JsonParam, {})
export default function App() {
  const [query, setQuery] = useQueryParams({
    json: MyParam
  });
  ...
}
``

**Comment by RomanTokar** [comment]
@pbeshai Thanks for help and thanks for this great package.
