### ISSUE TITLE
Not compatible with react router v6.4

### ISSUE THREAD

**Issue by iamyoki** [pbeshai/use-query-params#243]
React router v6.4 introduced a new way of creating router (https://reactrouter.com/en/main/routers/create-browser-router), so that leads to no longer possible to place `<QueryParamProvider /> `under `<RouterProvider />`

![image](https://user-images.githubusercontent.com/74389358/194073398-cd121374-dc85-4ed3-bc73-fd4832f41601.png)

**Comment by pbeshai** [comment]
Based on the linked docs, it seems like you should be able to just wrap the Root component with QueryParamProvider  – is this not the case? e.g.

```jsx
const router = createBrowserRouter([
  {
    path: "/",
    element: <QueryParamProvider><Root /></QueryParamProvider>,
    loader: rootLoader,
    children: [
      {
        path: "team",
        element: <Team />,
        loader: teamLoader,
      },
    ],
  },
]);

ReactDOM.createRoot(document.getElementById("root")).render(
  <RouterProvider router={router} />
);
```
