### ISSUE TITLE
can this works with found router?

### ISSUE THREAD

**Issue by DaniloOliveira28** [pbeshai/use-query-params#29]
Hi!

We are using the found library in our application. 

https://github.com/4Catalyzer/found

I am trying to discovery how to connect the use-query to found, it is possible out of box? Or, I need to create an adaptor?

Ty

**Comment by pbeshai** [comment]
Added an example: #44  https://github.com/pbeshai/use-query-params/tree/master/examples/found-router

Note this requires an update to serialize-query-params v0.1.4. This should install automatically with use-query-params. Alternatively, requires running `location.query = parse(location.search)` in the push and replace functions before calling router.push or router.replace.
