### ISSUE TITLE
Value of useQueryParam not updated after firing setter without third-party Router

### ISSUE THREAD

**Issue by colepeters** [pbeshai/use-query-params#30]
Thanks for your work on this library!

I'm using `useQueryParam` to get and set a value, e.g.:

```js
const [foo, setFoo] = useQueryParam('foo', NumberParam)
```

…but when I fire the setter, the value is updated only in the query string and not in the value returned from the hook. Am I missing something? I swear I see examples in the repo doing this very same thing and working… 😐

EDIT: The only thing I'm doing differently from the docs, if I'm reading things right, is that I'm not passing in anything about a routing library since I'm not using one in my app. Based on looking over the QueryParamProvider component source code, it looks like providing these props is optional?

Working example here — clicking the button will set `'foo'` to a random integer, but the value (which is rendered in the DOM) is only updated on refreshing the page: https://codesandbox.io/embed/cool-night-mv67g

EDIT 2: Just to see what happens, I've tried installing React Router and wrapping my app with BrowserRouter, passing the Route to QueryParamProvider. Things now work, but I have no other need for React Router (or routing of any kind at the moment). Is it not possible to use this lib without a third party router? Thanks!

**Comment by pbeshai** [comment]
It is likely you need to get the app to re-render when the history changes. 

What happens if you try something like this:

```js
class App extends Component {
  componentDidMount() {
    // force an update if the URL changes
    history.listen(() => this.forceUpdate());
  }

  render() {
    return (
      <div>
        Your App
      </div>
    );
  }
}
```

or

```js
const App = () => {
  const [, forceUpdate] = useReducer(x => x + 1, 0);
  React.useEffect(() => { 
    history.listen(() => forceUpdate());
  }, []);

  return <div>Your App</div>
}
```

**Comment by pbeshai** [comment]
I've added an example in via #39. See it here: https://github.com/pbeshai/use-query-params/tree/master/examples/no-router

**Comment by pbeshai** [comment]
Note that I added a dependency on [history](https://github.com/ReactTraining/history). This is because we need some way to know when the URL changes. The history built into the browser doesn't provide such a mechanism as far as I know (quick googling suggests monkey-patching it). If there are other mechanisms for listening to push/pop/replace in the URL and causing a re-render, they should work as well.

**Comment by colepeters** [comment]
@pbeshai Thanks a bunch for this, it all makes sense to me!
