### ISSUE TITLE
Is it possible to add an example with typescript?

### ISSUE THREAD

**Issue by DinoJay** [pbeshai/use-query-params#33]
First of all, thank you for your excellent work. It was never so easy to encode state in the url. Unfortunately, I'm struggling a bit to type the `useQueryParams` function in Typescript.
How do I have to define the two following functions to make the Typescript compiler pass?

```javascript
  const [query, setQuery] = useQueryParams({
    modalUserTypeOpen: BooleanParam,
    userTypeId: StringParam
  });
  const updateQuery = (u: DecodedValueMap): void =>
    setQuery({...query, ...u});
```
Thank You!
Jan

**Comment by pbeshai** [comment]
You shouldn't need to do that expansion to get partial updates working. setQuery by default only does partial updates (with setting `replaceIn` as the default). The TypeScript engine should infer the types.... I typically just use setQuery directly.

Note:

```
// query params = ?a=123&b=foo
setQuery({ a: 999 }) // --> ?a=999&b=foo

// query params = ?a=123&b=foo
setQuery({ a: 999 }, 'replace') // --> ?a=999
```

Options are `push`, `pushIn`, `replace`, `replaceIn`

**Comment by pbeshai** [comment]
This may also be helpful:

```js
import {
  StringParam,
  NumberParam,
  DecodedValueMap,
  SetQuery,
} from 'use-query-params';

const queryConfig = {
  zzz: NumberParam,
  test: StringParam,
  anyp: StringParam,
};

interface Props {
  query: DecodedValueMap<typeof queryConfig>;
  setQuery: SetQuery<typeof queryConfig>;
}
```
