### ISSUE TITLE
great server side addition

### ISSUE THREAD

**Issue by pocesar** [pbeshai/use-query-params#4]
if you could decouple the (de)serializing logic from React, and make it a dependency on this project, would be very easy to use on the server as well (as query-string works on node.js)

**Comment by pbeshai** [comment]
Hmm, that's an idea. I'll think about it! Could be handy.

**Comment by pbeshai** [comment]
FYI this is now available: https://github.com/pbeshai/serialize-query-params

Will be updating this project to use it.
