### ISSUE TITLE
Components wrapped in `React.memo()` do not update when the query params change

### ISSUE THREAD

**Issue by davidwallacejackson** [pbeshai/use-query-params#47]
If `useQueryParam()` is called within a component wrapped in `React.memo()`, the memoized component doesn't re-render when the params are changed.

Repro:
https://codesandbox.io/s/params-test-p9yxh

Try clicking the first `false` (next to "Unmemoized value:"). The query param in the URL gets set to 1, and the unmemoized value updates to true, but the memoized value stays the same. Clicking on the memoized value can cause the unmemoized value to change, but the memoized value itself still won't change.

I had hoped to submit a PR for this, but I'm still not sure what's causing it. As far as I know, calls to `useContext` should effectively override component memoization -- see a similar demo here: https://codesandbox.io/s/memoized-context-test-m4xpt

Edit: Here's a PR with a failing test, at least: https://github.com/pbeshai/use-query-params/pull/48

**Comment by pbeshai** [comment]
Hi, thanks for looking into this. While your test seems to cause a failure, I believe this is due to the isolated nature of the test and does not actually show a problem. The re-rendering should be caused via context changes which are powered by the router. I updated your code sandbox to use react-router the way I normally do, which makes it work properly.

https://codesandbox.io/s/params-test-pfdrz

The notable changes are:

```js
import { BrowserRouter as Router, Route } from "react-router-dom";
```

and 

```js
function App() {
  return (
    <Router>
      <QueryParamProvider ReactRouterRoute={Route}>
        <Route path="/" component={HomePage} />
      </QueryParamProvider>
    </Router>
  );
}
```

Note that it is important that QueryParamProvider is a descendant of Router so that it can use its context (it gets this indirectly through the Route component).

**Comment by davidwallacejackson** [comment]
Ah, you're right about the test -- it "fails" even when I get rid of the memoized wrapper. My bad.

As for your example, I noticed you're using react-router-dom 5.x -- I'm on react-router 3, unfortunately, and can't upgrade for a while. I tried to recreate your example here using 3.x, but the params just don't update at all -- is there some other workaround I could try for RR3 compatibility? Or some change I could make in a PR such that the API can work for both? I think the problem has to do with the fact that RR3 routes don't render the way normal components do, but I'm not sure.

**Comment by pbeshai** [comment]
Hi there, here's how you can get it working with react-router v3:

https://codesandbox.io/s/params-test-q54ts

The main changes are: 
- The QueryParamProvider must be a descendant of Router so it can get its context. In RR3 this means it needs to be a Route. So we wrap the provider in a Route with no specified path.
- The `history` object is actually called `router` (we want the one with `push` and `replace` functions) and is available as a routeProp so we can get it in our wrapper component.

```js
const QueryParamProviderRoute = ({ children, router, location }) => {
  return (
    <QueryParamProvider history={router} location={location}>
      {children}
    </QueryParamProvider>
  );
};

function App() {
  return (
    <Router.Router history={Router.browserHistory}>
      <Router.Route component={QueryParamProviderRoute}>
        <Router.Route path="/" component={HomePage} />
      </Router.Route>
    </Router.Router>
  );
}
```

It's a bit weird, but it works!

**Comment by davidwallacejackson** [comment]
Thank you so much for posting the workaround! I decided to make a push to try and get my project on to v5 after all, but if that doesn't work out it's great to know we have an alternative.

**Comment by pbeshai** [comment]
No problem!
