### ISSUE TITLE
Support for nested query parameters

### ISSUE THREAD

**Issue by lorefnon** [pbeshai/use-query-params#5]
I am creating a dashboard with multiple panels and was thinking it would be a good idea to support scoping of query parameters through a prefix. 

eg. `?sidebar-panel[id1][width]=100&sidebar-panel[id2][is-editing]=true&body-tile[0][placement]=0,0&body-tile[1][placement]=0,1`

[qs](https://github.com/ljharb/qs) library supports nesting and auto serializes/deserializes nested structures into query parameters like the above. 

I think it would be useful to have scoping supported in this library so that it becomes easy to configure a component to receive the query parameters scoped by component name (and optionally an id, in case of multiple components in the page). 

I believe this somewhat expands the scope of this library, but if you are ok with having this in the core, I would be interested in contributing the implementation for this.

I am not yet entirely sure of what the ideal API would look like, but I was thinking along the line of templated keys (similar to webpack):

```
const [foo, setFoo] = useQueryParam('[prefix].[id].foo', ArrayParam, { prefix: 'custom-component', id: this.props.id });
```

**Comment by pbeshai** [comment]
Hmm interesting syntax. I had handled these by using flat objects and either the ObjectParam setting or a custom param for my exact case. e.g. you could have

```js
const obj = { foo: 'abc', bar: 'def' }
```

And in the URL it'd be `?obj=foo-abc_bar-def`, which is reasonably concise. If you don't care about it being concise, you can use JsonParam which will give you 

```
?obj=%7B%22foo%22%3A%22abc%22%2C%22bar%22%3A%22def%22%7D
```

If you don't care about being concise but you find the encoding too ugly to consider, then I think the prefix can be helpful. 

Perhaps a way forward is to rename ObjectParam to FlatObjectParam or DelimitedObjectParam (similar to DelimitedArrayParam), and have the new ObjectParam work with nested encoding/decoding. Then we'd do something like

```js
const [sidebarPanel, setSidebarPanel] = useQueryParam('sidebar-panel', ObjectParam);
const [bodyTile, setBodyTile] = useQueryParam('body-tile', ObjectParam);
```

You would probably want your own param type to properly decode the nested types (ObjectParam would treat every value as a string). I'll think about this a bit more, thanks for bringing it up!

**Comment by pbeshai** [comment]
Upon further investigation, it seems at some point the react-router team moved away from `qs` to `query-string`, see here: https://github.com/ReactTraining/history/issues/121

Unless things have changed with qs since then (very possible!), it might be best we steer clear from it too.

**Comment by pbeshai** [comment]
I've decided against supporting this for now. See reasoning on [query-string](https://github.com/sindresorhus/query-string#nesting). Encoding as JsonParam should handle this case well enough, or creating your own type.

**Comment by lorefnon** [comment]
@pbeshai Thanks for investigating this and your detailed reply. 

I hadn't considered the size of qs before posting this and I understand if it is because of larger size that you don't want to switch to it. 

Most of the other arguments in the linked issues are moot as of now, esp. given the linked repo (node-querystring is pretty much defunct now and current maintainer of qs takes browser targets seriously). 

My primary suggestion was however, not to switch to qs, but to add support for scoping in query params - qs was just one implementation which I happened to have tried out myself. 

I agree that JsonParam handles much of this use case (query param scoping), however it is not perfect in the sense that consumer components have to handle merging themselves. So if I have two instances of same component (say Panel) that derive props from `panel[1]` and `panel[2]` respectively, then if using a single JSON parameter with panel, each parameter will have to ensure that they merge in the properties relevant to other panels. 

However I was able to use a combination of manual scoping and JsonParam to get pretty much what I wanted ([CodeSandbox](https://codesandbox.io/s/rjj21o064p)): 
```
useQueryParam(`counter[${id}]`, JsonParam);
```

The URLs are arguably a bit ugly with encoded JSON, but I can live with it for now.

**Comment by pbeshai** [comment]
Ah I think I get what you mean although I'm a bit lost by this part:

> I agree that JsonParam handles much of this use case (query param scoping), however it is not perfect in the sense that consumer components have to handle merging themselves. So if I have two instances of same component (say Panel) that derive props from panel[1] and panel[2] respectively, then if using a single JSON parameter with panel, each parameter will have to ensure that they merge in the properties relevant to other panels.

Do you think you could explain it with an example?

Glad that manual scoping solution worked for you for now, it seems like a reasonable approach to me. If the URLs are too ugly, I'd recommend just creating your own param type (just needs an encode and decode function). You can combine the existing encode functions to your liking which might make it easier. See [serialize.ts](https://github.com/pbeshai/serialize-query-params/blob/master/src/serialize.ts) and [params.ts](https://github.com/pbeshai/serialize-query-params/blob/master/src/params.ts).

**Comment by lorefnon** [comment]
> Do you think you could explain it with an example?

Yes, So imagine we have a metro-style dashboard where each tile derives its props from query params. 

We can have something like a `ClockTile` which shows a clock for a timezone that it gets from query params. Now we can have multiple `ClockTile` components in the dashboard so we want to scope the query params by lets say an id prop of each component. 

So I can say: 

```
<ClockTile id="tile-1" />
<ClockTile id="tile-2" />
```

Now if `ClockTile` used a query param `clockTileParams` with `JsonParam`, we end up with something like: 

`?clockTileParams=<json-encoded: { "tile-1" : { "tz" : "asia/kolkata" }, "tile-2" : { "tz" : "usa/pacific" }}>`

Now, every `ClockTile` component when it needs to update, it will have to ensure that it merges the existing query param value before invoking `setQueryParam` otherwise it will wipe off the query param for other ClockTile components. 

Not that this is something that can't be done easily, it is just that if scoping is supported by default (or we use namespaced keys) the merging would get auto-handled.

**Comment by marcelopm** [comment]
It would be nice to see this limitation listed in the README file
