### ISSUE TITLE
Values not loading on a server side render using <StaticRouter>

### ISSUE THREAD

**Issue by jordanrastrick** [pbeshai/use-query-params#51]
I'm having trouble getting `use-query-params` to correctly fetch query param values on a Server Side Render. We are using `<StaticRouter>` from `react-router-dom`, initialised as is standard with the known value of `location` from the request.

[Looking at the source here](https://github.com/pbeshai/use-query-params/blob/d7144abeadd27b86910b2b330751f106e0743141/src/useQueryParam.ts#L40-L48) it seems that the assumption is being made that on a SSR the query must be extracted from `location.pathname` rather than from `location.search`. However AFAICT `<StaticRouter>` puts the query string in `location.search` consistent with `<BrowserRouter>`. 

It seems like it might make more sense just to test directly for the presence of `location.search` and only fallback to parsing `pathname` if the former is missing, rather than checking for `window`? (although I'm not sure if this approach would be compatible with other routing frameworks...)

I will in the meantime workaround this using `rawQuery` but it'd be nice for it to work out of the box to reduce complexity and allow us to phase out other query string related packages completely in favour of just using this. 

Cheers.

**Comment by pbeshai** [comment]
I haven't used SSR, so the last fix was done by someone else who found it solved their problem (the window check). If you want to submit a PR for fixing this in a way that works better, please do

**Comment by jordanrastrick** [comment]
Sure, will do :-)

**Comment by Romcol** [comment]
Hi, I have the same problem with reach-router with 0.4.3 ! I found putting `QueryParamProvider` inside the Router and switching back to 0.4.2 did the trick:

`    <Router basepath="/">
      <QueryParamProvider default reachHistory={globalHistory}>
        //routes definition
      </QueryParamProvider>
    </Router>`

Actually we have to extract from `location.search` with reach-router.

Would be grateful for an update :-) I can help with the PR but not sure how to handle different configuration/router :+1:

**Comment by dante-blitz** [comment]
Thanks for the solution @Romcol. 

I cant seem to get it working with Gatsby.

Do you by any chance have this working in Gatsby?

**Comment by Romcol** [comment]
@dante-blitz Not with Gatsby but I have a similar SSR configuration as Gatsby/Next.js. Which router do you use? Reach router? React router?
