### ISSUE TITLE
Undefined values causing problems with inputs

### ISSUE THREAD

**Issue by Wizhi** [pbeshai/use-query-params#52]
This might be an unintended use of the hook, but it's a use nonetheless.

I have a component `Filter` which the user interacts with through `input` controls in order to specify a `filter`, which should then be used for searching. 

My goal is to have the `filter` saved to the url, so that the user may then link the search page, with the `filter` they specified. I figured that `useQueryParams` would cover this use-case as a kind of "drop-in replacement" for `useState`, which just so happens to load/save the state to the query string.

However, for parameters of the type `StringParam`, the `useQueryParams` hook seems to default "empty" values to `undefined` - seemingly in order to remove them from the query string - likely due to [the parameter encoder](https://github.com/pbeshai/serialize-query-params/blob/master/src/serialize.ts#L208).

This means that any state variables set by `useQueryParams` (or `useQueryParam`), will cause `input` controls to switch from being **uncontrolled** to **controlled** when the user enters an initial value, or vice-versa when the user deletes the value from the control, causing this warning:

```
Warning: A component is changing an uncontrolled input of type undefined to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
    in input (at src/index.js:32)
    in Filter (at src/index.js:55)
    in Route (at src/index.js:54)
    in Route (created by QueryParamProvider)
    in QueryParamProvider (at src/index.js:53)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:52)
    in App (at src/index.js:63)
```

Now, I've seen #31, and the [proposed solution](https://github.com/pbeshai/use-query-params/issues/31#issuecomment-520813670) by @albinekb seems workable for `useQueryParam`, but what about `useQueryParams`?

I'm not proposing adding default values for the query parameters, but I'd be happy to see some kind of solution to this problem. My simple idea of computing a `displayFilter` doesn't cut it.

Demo (with my failed attempt at solving the issue): https://codesandbox.io/s/bitter-moon-81gzo

**Comment by pbeshai** [comment]
You just need to have the value provided to the input field be `''` instead of undefined.

Some solutions:

```js
      <input
        value={displayFilter.query || ''}
        onChange={e => setFilter({ query: e.target.value })}
      />
```

Or

```js
const [filter, setFilter] = useQueryParams({
    query: StringParam,
    arbitrary: BooleanParam,
    solution: NumberParam
  });
const { query = '', arbitrary = false, solution = 42 } = filter;

...

      <input
        value={query}
        onChange={e => setFilter({ query: e.target.value })}
      />
```

Or you could combine those top two lines into:

```js
const [{ query = '', arbitrary = false, solution = 42 }, setFilter] = useQueryParams({
    query: StringParam,
    arbitrary: BooleanParam,
    solution: NumberParam
  });

```



Also note, you do not need to do `setFilter({ ...filter, query: e.target.value })`. by default, use-query-params does `replaceIn` which will remember existing filter values. so you can do `setFilter({ query: e.target.value })`.

**Comment by Wizhi** [comment]
The first solution is a bit awkward to work with, usually I'd expect all state to be valid for rendering, to minimize any logic there. Especially given my actual structure, wherein `Filter` is actually a child component of some `List` component, meaning the child component is highly aware of it's parent component, which doesn't seem ideal. It works though, so that's good.

The second and third solutions seem a lot cleaner. Only downside is that `filter` can no longer be passed around as an object, but I suppose you could get around this by destructuring as proposed, and then reassembling the object.

But maybe one should just embrace the primitives, and pass those to the `Filter` component instead. Since `replaceIn` is the default, having a singular `onChange` callback for the `Filter` component, which simply sends the singular filter property changed is still pretty clean.

I think I'll go with that, thanks a bunch!

**Comment by guzzijones** [comment]
I also wish an empty string would leave the paramter in the query with an empty value.
