### ISSUE TITLE
Can this work with Gatsby?

### ISSUE THREAD

**Issue by dante-blitz** [pbeshai/use-query-params#56]
Has anyone successfully used this with gatsby?

I'm trying to get this working but upon running 'gatsby build. I get the following error...

```WebpackError: TypeError: Cannot read property 'search' of undefined```

I've looked at similar issues but have not found a definitive answer.

**Comment by dante-blitz** [comment]
https://github.com/pbeshai/use-query-params/issues/13

**Comment by dante-blitz** [comment]
https://github.com/pbeshai/use-query-params/issues/51

**Comment by dante-blitz** [comment]
https://github.com/pbeshai/use-query-params/pull/55

**Comment by Romcol** [comment]
This could help : https://github.com/pbeshai/use-query-params/issues/51#issuecomment-546393827. See if it can help you!

**Comment by SimeonGriggs** [comment]
Also having this problem.

Whole thing works fine during development but can't get it to build. Same error as the OP.

**Comment by SimeonGriggs** [comment]
Got this working in Gatsby during Build! 

Bring in the `Location` component where you bring in `globalHistory`

```
import {globalHistory, Location} from '@reach/router'
```

Then wrap the `QueryParamProvider` and pass in the prop

```
<Location>
    {({location}) => {
        return (
        <QueryParamProvider location={location} reachHistory={globalHistory}>
            <Layout {...props} />
        </QueryParamProvider>
        )
    }}
</Location>
```

This worked for me, YMMV.

**Comment by davshoward** [comment]
> Got this working in Gatsby during Build!
> 
> Bring in the `Location` component where you bring in `globalHistory`
> 
> ```
> import {globalHistory, Location} from '@reach/router'
> ```
> 
> Then wrap the `QueryParamProvider` and pass in the prop
> 
> ```
> <Location>
>     {({location}) => {
>         return (
>         <QueryParamProvider location={location} reachHistory={globalHistory}>
>             <Layout {...props} />
>         </QueryParamProvider>
>         )
>     }}
> </Location>
> ```
> 
> This worked for me, YMMV.

@SimeonGriggs Where are you using this code? In a component or on html.js?

**Comment by SimeonGriggs** [comment]
Inside a component called LayoutContainer, in `/src/containers/layout.js`

**Comment by davshoward** [comment]
Got it working - but each "update" causes the page to scroll to the top - do you have the same issue?

**Comment by SimeonGriggs** [comment]
Nope. That must be something else.

**Comment by alexluong** [comment]
Hi folks, I took the liberty to create a plugin for this. It should help you simplify the process of setting this up by just using the plugin. Would be cool if you take a look and see if you can benefit from it!

Here's the package:

[`gatsby-plugin-use-query-params`](https://www.npmjs.com/package/gatsby-plugin-use-query-params)

**Comment by vebjorngronhaug** [comment]
@davshoward did you figure out what was causing the scroll-to-top on update?

**Comment by davshoward** [comment]
> @davshoward did you figure out what was causing the scroll to top on update?

I did not :-(

**Comment by alexhillel** [comment]
I have the scrolling up to top in Gatsby issue too and can't work out why it's happening... it would be amazing if it didn't do that!

**Comment by ThomasJanUta** [comment]
This issue can be closed. 

Answer to the question is: yes.

How? 

- @SimeonGriggs comment: <https://github.com/pbeshai/use-query-params/issues/56#issuecomment-590488389>
- XOR
- @alexluong plugin: <https://github.com/pbeshai/use-query-params/issues/56#issuecomment-602065657>

**Comment by louishugens** [comment]
Hi,

I'm trying to get rid of this but i can. It sticks even after i uninstalled it. why os? and how to remove it?

**Comment by cesarvarela** [comment]
This seems to have stopped working with Gatsby 4, every time I use setQuery Gatsby throws a 404 (even when setting the `reachHistory` prop). I ended up using the `navigate` function alongside `stringify`.

**Comment by wylee** [comment]
> This seems to have stopped working with Gatsby 4, every time I use setQuery Gatsby throws a 404 (even when setting the `reachHistory` prop). I ended up using the `navigate` function alongside `stringify`.

I'm having the same issue with Gatsby 4. When running `gatsby develop`, I get a 404 when setting params, but `gatsby build && gatsby serve` works.

I'm wondering if there's a way to configure `use-query-params` to use Gatsby's `navigate`. Otherwise, it's kind of a non-starter to use this with Gatsby since the iterating is so slow.

Alternatively, maybe something's borked in my Gatsby config that's causing this to happen.

**Comment by presto2116** [comment]
If anyone gets to this issue like i have, v2 of use-query-params has a reach router adapter. 

```
import { ReachAdapter } from 'use-query-params/adapters/reach';
```

Makes it very easy to use with gatsby now
