### ISSUE TITLE
use-query-params/lib/types"' has no exported member 'QueryParamConfig'.

### ISSUE THREAD

**Issue by pnegahdar** [pbeshai/use-query-params#57]
TS compilation issue with 4.3 and a few versions prior.

**Comment by pbeshai** [comment]
Can you provide an example reproducing this issue?

**Comment by pbeshai** [comment]
Hmm interesting, I think I see it. Let me investigate.

**Comment by pbeshai** [comment]
This seems to work fine for me:
```js
import { QueryParamConfig } from 'use-query-params';
```

Not sure how/why `lib/types` is being referenced for you

**Comment by AndrewKirkovski** [comment]
Having same issue with Typescript 3.6.4
Interesting that even getting rid completely of QueryParamConfig usage in project it's still an issue

**Comment by AndrewKirkovski** [comment]
I think I see the issue. NPM version is dirty and has 'params.d.ts' that is not really a part of build at all
That file has invalid declaration inside that is trying to import QueryParamConfig from incorrect location

**Comment by pbeshai** [comment]
Ah I see, I think there was an old file in there (param.js now comes from serialize-query-params). I've pushed a patch with 0.4.6 after rm'ing the lib directory... let me know if it works. I will add rimraf to the build now
