### ISSUE TITLE
Stringify Dates is not giving the expected result

### ISSUE THREAD

**Issue by philipp985** [pbeshai/use-query-params#63]
Hello,
thanks for the library. I have a question or maybe misunderstanding of the configuration.

`const [query, setQuery] = useQueryParams({`
        `tags: ArrayParam,
        status: ArrayParam,
        createdFrom: DateParam,
    });`

When I call
`const encodedQuery = stringify(query);`
the output is for example
`"?createdFrom=Tue%20Nov%2005%202019%2001%3A00%3A00%…itteleurop%C3%A4ische%20Normalzeit%29&status=Open"`

I would have expected the DateParam to be in the format YYYY-MM-DD like it is in the url. What do I need to configure in the stringify method to get this kind of formatting of the date?

Thanks for your help!

**Comment by pbeshai** [comment]
It can be confusing that I am also exporting the functions directly from the query-string library, where stringify comes from. To leverage the query parameter config of use-query-params, you'll want to use the [encodeQueryParams function](https://github.com/pbeshai/use-query-params#encodequeryparams)

e.g.

```js
import { encodeQueryParams, useQueryParams, ArrayParam, DateParam } from 'use-query-params';
const queryParamConfig = { tags: ArrayParam, status: ArrayParam, createdFrom: DateParam, };
const [query, setQuery] = useQueryParams(queryParamConfig);
const encodedQuery = encodeQueryParams(queryParamConfig, query);
```
