### ISSUE TITLE
Query params not synced in parent component?

### ISSUE THREAD

**Issue by kazie** [pbeshai/use-query-params#64]
So, I am currently using `0.4.5`.

And inside it I have something akin to this structure.

```jsx
const [value, setValue] = useQueryParam('value', StringParam);
const [otherThing, setOtherThing] = setState<boolean>(false)
...
function flipOtherThing() = { setOtherThing(old => !old) }
...
return (
    <ValueGetterComponent externalSetterForValue={setValue} />
    {<p>{value}</p>}
    <button onClick={flipOtherThing} />
)
```

(if above doesn't work, don't worry, I just freebased the above code).

----

The problem is that whatever is running and setting things with `setValue`, doesn't seem to refresh/re-render the current component (parent) until the state (separate thing) is changed.

Where I actually have this problem is I have maybe 4-6 query paramas, the _URL changes instantly_, but not the internal state of the parent component, until I change _some other_ state inside it by using a state setter. (example `flipOtherThing` above)
Once the state setter is called, all queryParams are in sync again.

---

Does my explanation make sense of what my problem is? Or should I try to explain it in some other way? :)

**Comment by pbeshai** [comment]
Are you using QueryParamProvider? See the example in the README (or others in the repo, will depend on your router)

e.g.,

```js
import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter as Router, Route } from 'react-router-dom';
import { QueryParamProvider } from 'use-query-params';
import App from './App';

ReactDOM.render(
  <Router>
    <QueryParamProvider ReactRouterRoute={Route}>
      <App />
    </QueryParamProvider>
  </Router>,
  document.getElementById('root')
);
```

**Comment by kazie** [comment]
Ofcourse I am using `QueryParamProvider`. Would it have worked otherwise in the regular case?

**Comment by pbeshai** [comment]
If you can reproduce it in a codepen I can take a look

**Comment by kazie** [comment]
So I solved it, thank you very much for the example again.

The problem I had was two-fold.

First:
```
 ReactRouterRoute={Route}
```
was missing. And things seemed to work anyway, which lead to the confusion.

Second;
```
Router
Route
```
Are very 'close' names which made it very hard to read and see that they're actually two different things.

---

But now it seems to work, like intended!
Thanks a lot!

**Comment by pbeshai** [comment]
Glad it all worked out!
