### ISSUE TITLE
Array props cause extra renders with useQueryParams

### ISSUE THREAD

**Issue by mikestopcontinues** [pbeshai/use-query-params#68]
Hi. It seems `useQueryParams` doesn't do a deep comparison on array params, resulting in a refresh even when the param itself doesn't change.

My use case is something like this...

```js
const ComponentWithArrayParam = memo(() => { 
  const [queryWith] = useQueryParams(['arrayParam']);
  return (<div/>);
});

const ComponentWithoutArrayParam = memo(() => { 
  const [queryWithout, setQueryWithout] = useQueryParams(['stringParam']);

  useEffect(() => {
    // NOTE: this causes ComponentWithArrayParam to update...
    setQueryWithout({stringParam: 'newString'}, 'replaceIn');
  }, []);

  return (<div/>);
});

function App() {
  return (
    <>
      <ComponentWithArrayParam/>
      <ComponentWithoutArrayParam/>
    </>
  );
}
```

**Comment by pbeshai** [comment]
Can you provide a codesandbox with this issue? I'm not sure I understand from the code above as it doesn't actually follow the useQueryParams API

**Comment by mikestopcontinues** [comment]
Hrm, I wrapped up that project soon after I posted this. And I haven't bumped into the issue in my current project. I'm honestly not sure what the issue was. I'm honestly afraid I simply posted this in the wrong repo. 🙈 Apologies!
