### ISSUE TITLE
ArrayParam: empty string is valid value

### ISSUE THREAD

**Issue by braco** [pbeshai/use-query-params#73]
Just want to start by saying thank you for the package! Has been a big help.

Something I'd consider a bug: with ArrayParam, setting ["", "foo"] will result in a value of ["foo"]. Empty strings are valid values, and this behavior is surprising. This should at the very least be documented, but I would argue that it's a bad default.

**Comment by pbeshai** [comment]
Ah yes, there was a similar issue with ObjectParam that someone submitted a PR for: https://github.com/pbeshai/serialize-query-params/pull/13 

If you want to go ahead and do it for ArrayParam I'll happily merge and update
