### ISSUE TITLE
document how to unset a parameter

### ISSUE THREAD

**Issue by aappddeevv** [pbeshai/use-query-params#79]
I thought there might be a UrlRequestType of "unset" but did not see one. Is there a way to unset a query parameter? I know I can replace all of them, but that's different than removing one specifically.

**Comment by pbeshai** [comment]
I believe the solution is just to set it to `undefined` explicitly, I'll verify and see if I can make it more clear in the docs.

**Comment by pbeshai** [comment]
Hmm perhaps not, I'll be updating this...
