### ISSUE TITLE
Testing with react-testing-library

### ISSUE THREAD

**Issue by ayepRahman** [pbeshai/use-query-params#80]
Is there an example of how can I this package with react-testing-library?

**Comment by dprgarner** [comment]
React Testing Library renders components in a similar testbed to the browser, so you should be able to set up a component test in a similar way to how you'd set this library up for use in the browser. The details of setting up your routing library for testing will be specific to the routing library that you're using, and you should check with that library's docs for information on how to test it (e.g. [React Router's docs](https://reacttraining.com/react-router/web/guides/testing), [React Testing Library's docs](https://testing-library.com/docs/example-react-router)).

React Testing Library is dogmatically against testing the implementation details of your components, so you shouldn't really need to do anything with the hooks directly in your tests: you should just assert on the behaviour of the components themselves, or perhaps the updated location itself if you need to check that the URL is changing.

Here's a React Router example that just asserts on the behaviour of the component itself:

```jsx
import React from 'react';
import { render, cleanup } from '@testing-library/react';
import { createMemoryHistory } from 'history';
import { Router } from 'react-router';
import { Route } from 'react-router-dom';

import { useQueryParam, NumberParam, QueryParamProvider } from 'use-query-params';

// An example counter component to be tested
const UseQueryParamExample = () => {
  const [x = 0, setX] = useQueryParam('x', NumberParam);
  return (
    <div>
      <h1>{`x is ${x}`}</h1>
      <button onClick={() => setX(x + 1)}>Change</button>
    </div>
  );
};

afterEach(cleanup);

// The test for the component
test('use query param example', () => {
  const history = createMemoryHistory({ initialEntries: ['?x=3'] });
  const { queryByText } = render(
    <Router history={history}>
      <QueryParamProvider ReactRouterRoute={Route}>
        <UseQueryParamExample />
      </QueryParamProvider>
    </Router>
  );

  expect(queryByText(/x is 3/)).toBeTruthy();
  queryByText(/Change/).click();
  expect(queryByText(/x is 4/)).toBeTruthy();
});
```

If you want to check that the URL is updating in your test, you can assert on `history.location.search` directly. If your query params are very simple, you could just go with something like:
```js
expect(history.location.search).toEqual('?x=4');
```
If you have multiple query params or are doing something more complex, you'll likely want to parse this string first. You could you `parse` from [query-string](https://github.com/sindresorhus/query-string#usage) to convert the search string into an object:
```js
expect(parse(history.location.search)).toEqual({ x: '4' });
```
...or if you want to be sure that the params are being serialised properly in your test, you could use `decodeQueryParams` from [serialize-query-params](https://github.com/pbeshai/serialize-query-params#decodequeryparams):
```js
expect(decodeQueryParams({ x: NumberParam }, parse(history.location.search)))
  .toEqual({ x: 4 });
```

**Comment by pbeshai** [comment]
See the examples / #89 for details

**Comment by ayansen979** [comment]
Hey how to accomodate this test config change with React router v6 ? https://github.com/pbeshai/use-query-params/issues/108
same is not working with tests.
