### ISSUE TITLE
`useQueryParam` together with `withDefault` can still return undefined?

### ISSUE THREAD

**Issue by hbf** [pbeshai/use-query-params#91]
I'm doing something like

```ts
const [age, setAge] = useQueryParam('age', withDefault(NumberParam, 100))
```

and realized that `age`'s result type is `number | undefined`. Is this expected? Am I using/understanding `withDefault` wrong?

It seems to me that [`useQueryParam`](https://github.com/pbeshai/use-query-params/blob/fc51870ff8a79a04c445580784bd0a952a03af9d/src/useQueryParam.ts#L85) could return just `[D2, …` instead of `[D2 | undefined, …` and this would solve the problem?

**Comment by pbeshai** [comment]
I think you are right, I forget why that | undefined is there.. maybe some weird typing issue I wasn't thinking about. If you can drop it and get it to compile / tests to work, that'd be great!

**Comment by pbeshai** [comment]
In v1.1.1

**Comment by hbf** [comment]
Wow, thanks so much for the quick feedback and fix!
