### ISSUE TITLE
Error importing stringify function

### ISSUE THREAD

**Issue by willemarcel** [pbeshai/use-query-params#94]
I tried to update from 0.6.0 to 1.1.1, but I'm having this error when importing stringify:

`import { encodeQueryParams, NumberParam, stringify } from 'use-query-params';`

`Attempted import error: 'stringify' is not exported from 'use-query-params'`

**Comment by pbeshai** [comment]
Hi @willemarcel, as of v1, we no longer export `query-string` functions directly and require `query-string` as a peer dependency. Please add it and import from `query-string` directly. Note that if you support IE11, I believe you'll want v5.1.1 otherwise you can use v6

```
npm install --save query-string
```

```
import { stringify } from 'query-string'
```
